<?php
/**********************************************************************************
 * Author: 	Kiner Shah
 * Date: 	26-Jan-2018
 **********************************************************************************/
	session_start();
	error_reporting(E_ERROR | E_PARSE);


	date_default_timezone_set('India/Mumbai');
	$date = date('Y-m-d');
	require('fpdf.php');
	$pdf = new FPDF('P', 'pt', 'A3');
	$pdf->AddPage();
	$pdf->SetFont('Arial', 'I', 9);
	$pdf->Cell(100, 20, 'This document was generated by DailyExpenseCalculator.', 0, 0, 'L', false);
	$pdf->SetFont('Arial', 'B', 12);
	$pdf->Ln();
	$pdf->Cell(100, 20, 'Date: '.$date, 0, 1, 'L', false);
	

	$tableObj = $_POST["generatePDF"];
	$tableObj = explode(',', $tableObj);
	$balanceObj = $_POST["generatePDFData"];
	if(isset($tableObj)) {
		$res_array = array("result" => true);
		//echo $res_array['result']."is ".$tableObj[0];
	}
	//print_r($res_array);
	$pdf->Ln();
	$count = 0;
	foreach($tableObj as $t1) {
		if($count == 0 || $count == 1) {
			$pdf->SetFont('Arial', 'B', 16);
		}
		else {
			$pdf->SetFont('Arial', '', 16);
		}
		if($count % 2 == 0) {
			$pdf->Ln();
			$pdf->Cell(100);
			$pdf->Cell(450, 50, $t1, 1, 0, 'C', false);
		}
		else {
			$pdf->Cell(150, 50, $t1, 1, 0, 'C', false);
		}
		$count = $count + 1;
	}
	$pdf->Ln();
	$pdf->Cell(300, 50, "Balance: ".$balanceObj, 0, 0, 'L', false);
	ob_get_clean();
	$pdf->Output('F', 'pdf-'.$date.".pdf", true);
	ob_end_clean();
?>
<!--<script>
/* // To check if AJAX is supported
	if(window.XMLHttpRequest) {
		alert("Hello");
	}
	else {
		alert("yeay");
	}
*/
</script>-->